Add my example to the repo
ndcbe/cbe67701-uncertainty-quantification pull request #42
Opened 2020-07-07 21:46 UTC by xiangao1

I added an example of using the Gauss-Hermite quadrature to approximate the probability distribution of QoI with normal distributed input parameter.

2020-07-08 13:52 UTC, adowling2 approved these changes

2020-07-08 13:54 UTC, adowling2 requested changes
@xiangao1 Please add a section at the top to cite any references used for the code, text, or examples.

2020-07-08 13:54 UTC, adowling2 commented
@xiangao1 Here is an example of citing references:
https://ndcbe.github.io/cbe67701-uncertainty-quantification/07.01-Sampling-Based-Uncertainty-Quantification.html

2020-07-08 14:43 UTC, xiangao1 commented
References added.

2020-07-09 14:48 UTC, adowling2 approved these changes

2020-07-09 14:48 UTC, merged